### ISSUE TITLE
Welcome to Project Mapple !!

### ISSUE THREAD

**Issue by BRAVO68WEB** [chirag3003/project-maple#1]
_Read more about it in [README.md](https://github.com/chirag3003/project-maple/)_

### *This Issue will be acting as a mega-thread for Project Roadmap*

# Roadmap

## Current Sprint

- [ ] To Do Store
- [ ] Paste Bin
- [ ] File Storage
- [ ] CloudFlare Integration

## Upcoming Sprint

- [ ] Password Manager
- [ ] Docker/Code Snippet
- [ ] Status Page
- [ ] Build-In Web-based DevToys [Ref](https://github.com/veler/DevToys)
- [ ] Setting Backup
- [ ] Browser Extensions
- [ ] Wakatime Dashboard (Init)
- [ ] SAML 
- [ ] Backup Integration (restic)
- [ ] Log Tracking
- [ ] Mail REST API
- [ ] Notification System
- [ ] DB launcher
- [ ] Dashy Integration
